### ISSUE TITLE
DABUILD_PACKAGES no default value

### ISSUE THREAD

**Issue by OTLabs** [alpinelinux/docker-abuild#10]
I see no way to configure default value for DABUILD_PACKAGES so I need to specify it on command line all the time.

**Comment by mor1** [comment]
The default value is specified at <https://github.com/alpinelinux/docker-abuild/blob/master/dabuild.in#L53> using the `${VAR:-DEFAULT}` syntax. Or do you mean that you'd like to set a different default value?

Doh. The test for `$DABUILD_PACKAGES` being empty is before the default is applied. Fixing...

**Comment by mor1** [comment]
Should be fixed in 59aa1ab111bc8489684ef204c64e7e35c76e9cec. Closing.

**Comment by OTLabs** [comment]
Thank you!
