### ISSUE TITLE
Use of %%ALPINE_TAG%% for local repos

### ISSUE THREAD

**Issue by OTLabs** [alpinelinux/docker-abuild#14]
https://github.com/alpinelinux/docker-abuild/blob/c5508e242ebc64e0c5018ac115c3dff8d3ae77ba/Dockerfile.in#L7

I am not sure we should use `%%ALPINE_TAG%%` in path for local repos. I think `abuild` uses `.../packages/[main|community|testing]/...`.

Right now volume mounting do not take `%%ALPINE_TAG%%` into account and this leads to following errors for `edge`:
```
cd aports/testing/zimwriterfs
...
>>> zimwriterfs: Uninstalling dependencies...
WARNING: Ignoring /home/builder/packages/edge/main/x86_64/APKINDEX.tar.gz: No such file or directory
WARNING: Ignoring /home/builder/packages/edge/community/x86_64/APKINDEX.tar.gz: No such file or directory
WARNING: Ignoring /home/builder/packages/edge/testing/x86_64/APKINDEX.tar.gz: No such file or directory
```

**Comment by mor1** [comment]
I guess this is naivety on my part about workflows involving `abuild`.
I'd put the `%%ALPINE_TAG%%` in the path for local repos in case developers would want to build their packages for different versions simultaneously.
If that's really uncommon (or never happens), then yes, should just be removed (per #13).
Otherwise, I should just fix the bind mount paths to mount in appropriately (that's just a bug on my part :)

Thoughts?

**Comment by OTLabs** [comment]
Maybe moving the `%%ALPINE_TAG%%` in front of `/packages/`, with corresponding adjustment in volume mounting scheme, could achieve what you wanted? I just do not know how to teach `abuild` to use `packages/%%ALPINE_TAG%%` path ;-) Personally I plan to develop for edge for some time, but that could change in (near) future Or not.

**Comment by mor1** [comment]
Happy to do that, sure :)
@tcely Would that make sense to you, or better simply to remove the tag completely?

**Comment by tcely** [comment]
It doesn't make sense to me. The path to packages is set by default in abuild and everything under that directory is generated during the build process. If you want to have distinct repositories per tag, you should adjust the mount as that is easiest.

**Comment by mor1** [comment]
Doh. Yes, that makes sense. I've attempted adjust in the mount via a5585a7caecb3fe86aa30aafc0e55b18a7834bc7
