### ISSUE TITLE
abuild-keygen generated keys are not preserved between runs

### ISSUE THREAD

**Issue by OTLabs** [alpinelinux/docker-abuild#15]
https://github.com/alpinelinux/docker-abuild/blob/c5508e242ebc64e0c5018ac115c3dff8d3ae77ba/entrypoint.sh#L13

I feel that this code will run every time as the check will return true all time as this directory will be not preserved between runs. This could lead to that with each run the new key pair will be generated and already signed index files will be rendered as un-trusted as they will be signed with one key pair and later they will be intended to be signed with fresh generated key pair.

Maybe we can move key generation to Dockerfile?

**Comment by mor1** [comment]
That directory (`$HOME/.abuild`) is bind mounted from `$HOME/.abuild` on the host (`$HOME` in the image should be `/home/builder` given the user specified in the image), so it should persist between runs I think...? Or have you observed that it isn't?

I wouldn't want to put key generation in the Dockerfile because that would require everyone to build the images themselves, and I had been moving away from that (so you can now just `make dabuild` and then run the script, using the images that I've published on Docker Hub).

**Comment by OTLabs** [comment]
You are absolutely right about `.abuild`, my fault. And yes, you are also right about key generation in the Dockerfile.

There is just one issue related with `-a` switch: as it writes some info to `/etc/...` directory so it would not be persist between runs, but I assume I have an idea how to solve that. I hope to provide the patch.

**Comment by mor1** [comment]
Ah! I didn't realise that. It looks like it's `/etc/apk/keys/` that gets updated? If so, then bind mounting that from something under `$HOME/.abuild` on the host would be how I'd do it -- happy to patch if you haven't time :)

**Comment by OTLabs** [comment]
I was not thinking to add additional mount point. I was thinking to use 

```
abuild-keygen -i -a << EOF
/home/builder/.abuild/newkey_static_filename
EOF

```
and copy this key later in same script to `/etc/apk/keys/`

In Dockerfile we might need to write to some file in `/etc/...` the name of `newkey_static_filename`, I just forgot which file we need to modify. It comes from `-a` option.

That I was thinking to do.

**Comment by mor1** [comment]
Ah ok. Well, PR welcome :)
(Meanwhile I should probably spend a few moments and actually understand what `abuild-keygen` and `abuild` are doing!)

**Comment by tcely** [comment]
https://github.com/alpinelinux/docker-abuild/blob/a5585a7caecb3fe86aa30aafc0e55b18a7834bc7/entrypoint.sh#L11-L14

After keys are generated, we should copy `*.pub` to `/etc/apk/keys` so that persisted packages / repositories can be verified.
