### ISSUE TITLE
2 build targets for Docker image

### ISSUE THREAD

**Issue by OTLabs** [alpinelinux/docker-abuild#16]
`make images` build the Docker image and tries to upload it.

I try some ideas with Docker image and run `make images` quite often. It builds the image and tries to upload it producing the error. I do not like error messages. So...

What you think if we will have 2 build targets: one to only build the image and the second one to build and upload the image?

**Comment by mor1** [comment]
Sure; in fact, there are already separate targets, I just made `images` depend on `push` as well.

Should be fixed in b89760752fa186ce523a1c89875b2971465d8439

**Comment by OTLabs** [comment]
Thank you!
