### ISSUE TITLE
Naming and namespace

### ISSUE THREAD

**Issue by clandmeter** [alpinelinux/docker-abuild#20]
Currently the default namespace is mor1/dabuild. I would like to put the images under the alpinelinux namespace. Should we also change the image name to docker-abuild to make it less confusing?

We also discussed to not explicitly define the ORG in the makefile to prevent mistakes, but I think it makes sense dabuild has the correct location to the image so we do not have to provide that manually when creating the dabuild script. We should probably define a separate push ORG so we can keep that empty?

**Comment by mor1** [comment]
Agree: we should put images under `alpinelinux` and happy to change name of image (not script), and that having a separate push ORG will achieve the same goal while letting us make the default the working, common case.

**Comment by mor1** [comment]
Based on commit e064a62a43311ee2d9e38062b81bd875aaabc4dd I think this can be closed can't it? Please reopen if not... :)
