### ISSUE TITLE
Apple filesystem issues with abuild

### ISSUE THREAD

**Issue by clandmeter** [alpinelinux/docker-abuild#21]
When you try to build a package which uses special filesystem features on MacOS abuild with error.
To reproduce one can build bash and it will error.

**Comment by mor1** [comment]
Have reproduced. Looking into it.

**Comment by mor1** [comment]
This appears to be only with the untarring of the source tarball -- subsequent to that, the package builds just fine (except for some failing tests). Still investigating...

**Comment by mor1** [comment]
Ok. Problem appears to be that the ordering of files in the tarball has the symlink `bash-5.0/ChangeLog -> bash-5.0/CWRU/changelog` *before* `bash-5.0/CWRU/changelog`. Both files appear to be untarred ok, but (presumably) some syscall is invoked to set the utime on `bash-5.0/ChangeLog` when it's created, before its target exists, and that fails. Subsequent runs do see both files, including a valid symlink and so the `utime` can be set and everything can build just fine.

Will look into what's actually triggering the `Cannot utime` error next.

**Comment by mor1** [comment]
Right. This is a result of the `tar` extraction getting an error on the first run through and the build stopping there. Appears to be when it tries to set the `mtime` of a symlink whose target does not yet exist. Once the target exists, the build runs to completion.

A hacky workaround for this package might be to create the target by hand during the `prepare` phase in the `APKBUILD`, but that's a bit grim. (Or tell `abuild` to ignore errors during build and carry on regardless?) 

I'm following up to see if there's an underlying bug somewhere else.

**Comment by mor1** [comment]
The suspicion is that this is a bug in the D4M filesystem interface code. I didn't manage to track it down, but did speak with a (now ex-) colleague at Docker about it and I understand that there's work in the pipeline that might fix it. Am going to close this issue now as it's out of my hands -- I don't think there's anything I can do to work around it automatically.
