### ISSUE TITLE
Check that $REPODEST is writeable

### ISSUE THREAD

**Issue by Cogitri** [alpinelinux/docker-abuild#22]
I guess this might fall under user error, but it'd be nice if dabuild checked that `REPODEST` (from abuild.conf) is writable.

**Comment by mor1** [comment]
How does `REPODEST` in `abuild.conf` get set?
If it's something `dabuild` does, then yes definitely.
If it's something that the user set, I'm inclined to think that it's either the user's problem or `abuild`'s problem :)

**Comment by Cogitri** [comment]
It's set by the user, so I guess this should be handled better by abuild.
