### ISSUE TITLE
entrypoint.sh now updates packages on every run

### ISSUE THREAD

**Issue by mor1** [alpinelinux/docker-abuild#23]
Invoking `sudo apk -U upgrade -a` in `entrypoint.sh` significantly slows down invocation of `dabuild` because the updates aren't cached so have to be applied every time.

Better would be to autobuild and update the `alpinelinux/docker-abuild` images on Hub when packages are updated I think -- is that feasible?

/cc @clandmeter @tcely

**Comment by tcely** [comment]
@mor1 I think we can also run the upgrade in the `Dockerfile` also to eliminate some of the work.

**Comment by mor1** [comment]
Yes; I guess the thing is to make sure the images are rebuilt whenever a package is updated though (to achieve the same effect as currently).

**Comment by clandmeter** [comment]
We need to make sure world is up to date when building packages.
I guess we need to implement automatic image updates on drone, and maybe
some auto pull feature in dabuild.
To speed up upgrades we need apk cache so only the first upgrade takes some
time and the next will use local apk cache.

**Comment by mor1** [comment]
The upcoming `--pull` flag for `docker run` will do that (I believe it missed the 19.03 cut-off though); in the meantime I can explicitly `docker pull` in the shell script before doing the `docker run`.

Not sure how using an apk cache will help -- the upgrade step would still need to run each time.

(Actually I think there would also be benefits to doing this via `docker pull` -- you'd be able to know precisely which state of the world was used for any given build since the image version would identify that.)
