### ISSUE TITLE
tests which bind to ports fail

### ISSUE THREAD

**Issue by Cogitri** [alpinelinux/docker-abuild#25]
E.g. libgdata's tests fail in docker-abuild but not with `abuild -r`:

```
ERROR: oauth2-authorizer - Bail out! libuhttpmock:ERROR:libuhttpmock/uhm-server.c:1398:uhm_server_run: assertion failed (error == NULL): Could not listen on address ::1, port 35143: Error binding to address: Address not available (g-io-error-quark, 0)
ERROR: youtube - Bail out! libuhttpmock:ERROR:libuhttpmock/uhm-server.c:1398:uhm_server_run: assertion failed (error == NULL): Could not listen on address ::1, port 41085: Error binding to address: Address not available (g-io-error-quark, 0)
```

**Comment by mor1** [comment]
Looks like maybe an IP V6 support issue to me. Will take a look when next
at proper computer. Can you force the tests to IP v4 only? Does it make a
difference?

**Comment by Cogitri** [comment]
Use https://github.com/alpinelinux/aports/pull/7597 for testing for now, until that's merged.

> Can you force the tests to IP v4 only?

Don't think so, but I can give it a try

**Comment by mor1** [comment]
Sorry for delay. Judging by discussion on https://github.com/alpinelinux/aports/pull/7597 this is indeed a Docker-doesn't-do-IPv6 problem. I'll note the issue in the README but don't have a fix for it at this time.

**Comment by Cogitri** [comment]
Yup, a note in the readme does the trick for me :)
