### ISSUE TITLE
How to install git related libraries into Alpine linux

### ISSUE THREAD

**Issue by rifaterdemsahin** [alpinelinux/docker-abuild#40]
my current distro

bash-4.4# cat /etc/os-release

NAME="Alpine Linux"

ID=alpine

VERSION_ID=3.9.4

PRETTY_NAME="Alpine Linux v3.9"

HOME_URL="https://alpinelinux.org/"

BUG_REPORT_URL="https://bugs.alpinelinux.org/"

bash-4.4#

----------------

terraform init -from-module="git::ssh://xxxx

Init works with the repo my local using -from-module but does not work in docker Alpine that was provided by Hashicorp!!!!

What other libraries do I need?

How can I see the error on my container? ( the terraform does not give me the reason I had to find it after trying multiple points )

Here is my docker file I am using at the moment

FROM hashicorp/terraform:0.11.14 AS main

RUN apk -v --update add ncurses
RUN apk -v --update add bash
RUN apk -v --update add git
RUN apk -v --update add openssh
RUN apk -v --update add openssl-dev
RUN apk -v --update add expect
RUN apk -v --update add python
RUN apk -v --update add py-pip

RUN pip install --upgrade awscli==$aws_cli_version
RUN pip install azure-devops==5.0.0b9

RUN apk -v --purge del py-pip curl &&
rm /var/cache/apk/*

The reason i am looking into this is a git module of Terraform is not working I think there a missing dependency

https://github.com/hashicorp/terraform/issues/22791

**Comment by mor1** [comment]
Hi! I don't think this is a good repo to post this issue against -- `docker-abuild` is simply a script to allow Alpine package developers/maintainers to run `abuild` in a container so that those of use who don't have Alpine on our desktops (but do have Docker) can more easily develop and maintain packages. It doesn't seem like this will be connected with your issue at all. (But do reopen if I've missed something.)

**Comment by jalalkhann1245e-glitch** [comment]
> Hi! I don't think this is a good repo to post this issue against -- `docker-abuild` is simply a script to allow Alpine package developers/maintainers to run `abuild` in a container so that those of use who don't have Alpine on our desktops (but do have Docker) can more easily develop and maintain packages. It doesn't seem like this will be connected with your issue at all. (But do reopen if I've missed something.)

Can you help me in hacking skills
