### ISSUE TITLE
ARCH detection fails on pi raspbian

### ISSUE THREAD

**Issue by macmpi** [alpinelinux/docker-abuild#41]
`uname -m` on raspbian may give `armv6l` on rpi0 for instance, which clashes wrt  expected `armhf` tests
https://github.com/alpinelinux/docker-abuild/blob/master/Makefile#L19
https://github.com/alpinelinux/docker-abuild/blob/master/dabuild.in#L27

**Comment by mor1** [comment]
Ugh :(
I'm not familiar with rpi0 behaviours -- what would be the appropriate thing to do in this case? Should I call `uname` differently, or do I just need to add `armv6l` as an acceptable architecture?

**Comment by macmpi** [comment]
Actually `uname` on Pi devices will either respond `armv6`, `armv7`, `armv7l` or `armv8` depending on devices and relative [kernel selection](https://github.com/Hexxeh/rpi-firmware). For sure none will report `armhf` with `uname`.

If on Debian, ``` ARCH=`/usr/bin/dpkg --print-architecture` ``` will give you the right thing for sure.
Exemples [here](https://unix.stackexchange.com/questions/12453/how-to-determine-linux-kernel-architecture), which also refer to syscap (that may not be debian-centric?)

**Comment by mor1** [comment]
Hopefully fixed via 76335533f5bff8e961ace9ed4d7585d67c45844c -- reopen if it doesn't work, and I'll look again. Thanks!

**Comment by macmpi** [comment]
Thanks: may take me a while to test as my Pi fried last week in thunderstorm!... Will report then if issues.
Maybe error message could give clue of variable name to be set as a calling convention when detection fails (and maybe document it upfront in README)?

It looks like `makefile` also has an `ARCH := $(shell uname -m)` statement that could case problems. (I remember I did modify both scripts to spell-out the wanted ARCH)

**Comment by mor1** [comment]
Re error message -- good point, will add (and to README).
Re `Makefile` -- AFAICS I'm only using it in the `Makefile` to distinguish the different images that are built, so I don't think it actually matters what string is produced by `uname -m` there, so long as it's consistent across platforms.

**Comment by macmpi** [comment]
Actually it does not work since those reported architectures are not supported in [docker abuild](https://hub.docker.com/r/alpinelinux/docker-abuild/tags) anyway. One option could be to complexify architecture detection and make more special cases to fill-in supported architectures accordingly. Not sure it is very safe approach.
Proposed a fix https://github.com/alpinelinux/docker-abuild/pull/44/commits/7290bff53364768aea4dd083392b04a26b165f33 that just gives a hint to set variable before invocation to force architecture value.

`Readme` needs changes too I'm afraid: maybe spelling-out usage of `DABUILD_ARCH` & `DABUILD_VERSION` invocation variables would help too.

Hope this helps, and sorry for confusion.

**Comment by macmpi** [comment]
@mor1 did you have a chance to review https://github.com/alpinelinux/docker-abuild/commit/7290bff53364768aea4dd083392b04a26b165f33 as https://github.com/alpinelinux/docker-abuild/commit/76335533f5bff8e961ace9ed4d7585d67c45844c is not working properly?

**Comment by mor1** [comment]
Sorry, hadn't. Now have - will merge. Thanks!

**Comment by macmpi** [comment]
Hope this helps.
Readme may need to be adapted too with `DABUILD_ARCH` & `DABUILD_VERSION` invocation variables usage.
