### ISSUE TITLE
Image isn't removed after the command is done

### ISSUE THREAD

**Issue by PureTryOut** [alpinelinux/docker-abuild#42]
This causes the filesystem to fill up if you don't manually clean up the images every once and while (e.g. `docker system prune`). I have this issue constantly as I tend to build large groups of packages at once (like KDE updates) using a script. Halfway such a process my system is filled up by leftover docker images from docker-abuild, and there isn't enough disk space to continue.

**Comment by mor1** [comment]
Ah, that's a problem. Does #43 work for you as a solution?

**Comment by PureTryOut** [comment]
Yeah that seems to do the trick, thanks!

**Comment by mor1** [comment]
Closed by #43 (50936533d25f08eaa5c0f04499cd377c137017e2)
