### ISSUE TITLE
ccache should not use hosts ccache store

### ISSUE THREAD

**Issue by clandmeter** [alpinelinux/docker-abuild#48]
I dont think it's wise to share this with the host, for sure when users are allowed to use different arches. Instead I would suggest to use docker volumes based on arch.

ref  #36

**Comment by mor1** [comment]
@clandmeter think that fixes it.
@jbenden you may wish to check that the fix doesn't break ccache usage for you?

**Comment by jbenden** [comment]
The change seems good! Thanks!
