### ISSUE TITLE
move developement and ci to gitlab.a.o

### ISSUE THREAD

**Issue by clandmeter** [alpinelinux/docker-abuild#50]
Would be nice if we could move development to gitlab and let it use gitlab ci.
The periodic build of images with drone cloud seems not supported, need to check if we can fix this within gitlab CI. @Ikke any idea?

**Comment by Ikke** [comment]
Gitlab let's you create scheduled pipelines, which are already used to rebuild several images weekly.

**Comment by mor1** [comment]
Happy to move the repo to gitlab.a.o (wasn't sure why it hadn't been moved already tbh :)

Ditto gitlab CI/pipelines. What needs to be done?

**Comment by clandmeter** [comment]
@Ikke are you able to help with setting up CI? I can try but you have more experience with GitLab CI.

**Comment by Cogitri** [comment]
While moving this, please [import the repo](https://docs.gitlab.com/ee/user/project/import/repo_by_url.html) so issues etc. stay intact :)

**Comment by clandmeter** [comment]
I have now migrated this project to gitlab. We need to close functions and mention it has moved.

/cc @mor1
