### ISSUE TITLE
Clarify dabuild multi arch support 

### ISSUE THREAD

**Issue by clandmeter** [alpinelinux/docker-abuild#51]
It looks to me that only docker on MacOS can support multi-arch as can be read here:
https://docs.docker.com/docker-for-mac/multi-arch/

This makes it easy to run dabuild for a different arch with qemu emulation (its slow but it would work).
I have tried this on Docker on Linux but it doesnt seem to work in the same way. I can also not find any reference for multi-arch for other platforms except the link above.

**Comment by clandmeter** [comment]
This seems to work: https://github.com/multiarch/qemu-user-static

**Comment by mor1** [comment]
Yes-- the `binfmt_misc` hack to support multiarch images by invoking qemu is only in the VM for D4M.

Best way to clarify this -- just add something to the README, or worth trying to detect environment and error out?

**Comment by clandmeter** [comment]
I guess we can add the qemu-user-static docker thingy?

and mention they need to exec:

docker run --rm --privileged multiarch/qemu-user-static --reset --persistent yes --credential yes

where credential fixes the sudo issue.

**Comment by mor1** [comment]
Closed via b793e3e7370a768df9c469b117c2bda360d09017

**Comment by clandmeter** [comment]
To fix the sudo thingy you command should be:

docker run --rm --privileged multiarch/qemu-user-static --reset --persistent yes **--credential yes**

I think it would also be nicer to rename the item in the readme to:

## Configure  multi-arch support

in which to mention it will work out of the box for Mac but needs a fix for linux.

Maybe also mention this will use cpu emulation which will reduce cpu performance.

**Comment by mor1** [comment]
Done, thanks :)
