### ISSUE TITLE
what does "Supported architectures" mean?

### ISSUE THREAD

**Issue by clandmeter** [alpinelinux/docker-abuild#53]
Looking at the readme we support

- x86
- x86_64
- aarch64
- armv6
- armv7
- armv7l
- armv8

but alpine only has support for:

- aarch64
- armhf
- armv7
- ppc64le
- s390x
- x86
- x86_64

ppc64le and s390x will be added ones we switch to GitLab CI.

**Comment by mor1** [comment]
Cf #44 -- it refers to those architectures for which we're autobuilding alpine container images that can be pulled from Docker Hub.

**Comment by clandmeter** [comment]
So the list is incorrect?

```shell
case "$DABUILD_ARCH" in
  x86|x86_64|aarch64|armhf|armv7 ) ;;
  * ) die "Unsupported arch \"$DABUILD_ARCH\" detected." \
          "Expected one of: x86|x86_64|aarch64|armhf|armv7" \
          "You may force it setting DABUILD_ARCH=\"xxx\" in invocation";;
esac
```

**Comment by macmpi** [comment]
indeed README should be fixed: a misunderstanding in https://github.com/alpinelinux/docker-abuild/issues/41 led to erroneous list in README, while code has been fixed since.
