### ISSUE TITLE
Run some operations with normal abuild

### ISSUE THREAD

**Issue by Cogitri** [alpinelinux/docker-abuild#8]
It'd make sense to run some operations (e.g. abuild checksum, unpack) via the normal `abuild` script, if it's detected on the system so that we don't have to create a new container just for these simple operations.

**Comment by mor1** [comment]
Thinking about this, it'll make the script a fair bit more complicated. Now that it's been renamed to `dabuild`, isn't it as easy for the user to make this decision themselves by explicitly running either `dabuild` or `abuild`?

I'm closing therefore, but please reopen if you think that there's a good argument for why it would still be useful :)
